const fs = require('fs');
const file = 'C:/Aman/SNMP-RMSApp/src/screens/History/SiteLogsScreen.tsx';
let code = fs.readFileSync(file, 'utf8');

code = code.replace(
    "                      {columns.map(col => {\n                          if (['site_name', 'site_id', 'global_id', 'globel_id', 'gsm_imei_no'].includes(col)) return null;\n                          return (\n                              <View key={col} style={LC.detailRow}>\n                                  <Text style={LC.detailLabel}>{colLabel(col)}</Text>\n                                  <Text style={LC.detailValue}>{col === 'state_id' && globalFilters?.state_name && globalFilters.state_name !== 'All' ? globalFilters.state_name : col === 'dist_id' && globalFilters?.district_name && !globalFilters.district_name.includes('Select') ? globalFilters.district_name : col === 'cluster_id' && globalFilters?.cluster_name && !globalFilters.cluster_name.includes('Select') ? globalFilters.cluster_name : fmtVal(col, row[col])}</Text>\n                              </View>\n                          );\n                      })}",
    "                      <View style={{ flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }}>\n                      {columns.map(col => {\n                          if (['site_name', 'site_id', 'global_id', 'globel_id', 'gsm_imei_no'].includes(col)) return null;\n                          return (\n                              <View key={col} style={[LC.detailRow, { width: '48%', flexDirection: 'column', alignItems: 'flex-start', borderBottomWidth: 0, paddingVertical: 6, backgroundColor: '#f8fafc', borderRadius: 8, paddingHorizontal: 8, marginBottom: 8 }]}>\n                                  <Text style={[LC.detailLabel, { marginBottom: 2, fontSize: 11 }]}>{colLabel(col)}</Text>\n                                  <Text style={[LC.detailValue, { textAlign: 'left', maxWidth: '100%', color: '#0f172a' }]}>{col === 'state_id' && globalFilters?.state_name && globalFilters.state_name !== 'All' ? globalFilters.state_name : col === 'dist_id' && globalFilters?.district_name && !globalFilters.district_name.includes('Select') ? globalFilters.district_name : col === 'cluster_id' && globalFilters?.cluster_name && !globalFilters.cluster_name.includes('Select') ? globalFilters.cluster_name : fmtVal(col, row[col])}</Text>\n                              </View>\n                          );\n                      })}\n                      </View>"
);

fs.writeFileSync(file, code);
console.log('Patched LogCard to 2-column grid layout');
